name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Deno
      uses: denolib/setup-deno@v2
      with:
        deno-version: 1.3.0

    - name: Test
      run: |
        deno test --allow-all --unstable
